# .goreleaser.yaml
project_name: wp-go-epub
builds:
  - id: linux_amd64
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archives:
  - id: linux_amd64
    builds:
      - linux_amd64
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_amd64"
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: henrikor
    name: wp-go-epub

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

before:
  hooks:
    - go mod tidy

# Release only when a tag matching "v*" is pushed
release:
  github:
    owner: henrikor
    name: wp-go-epub
    tag_template: '{{ .Tag }}'
    skip_if_no_tag: true
    draft: false
    prerelease: false
    name_template: '{{ .Tag }}'
    body_template: |
      {{ range .Notes }}
      - {{ . }}
      {{ end }}
