# .goreleaser.yaml
version: 2

project_name: ditt_prosjekt_navn

builds:
  - id: linux_amd64
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    main: .
    ldflags:
      - "-s -w"
    hooks:
      pre: go mod tidy

archives:
  - id: linux_amd64
    builds:
      - linux_amd64
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_amd64"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

release:
  github:
    owner: ditt_github_brukernavn
    name: ditt_repositorienavn
    token: "{{ .Env.GITHUB_TOKEN }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

before:
  hooks:
    - go mod tidy
