name: Go

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Clean Git State
      run: git reset --hard

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        
    - name: Run GoReleaser
      run: goreleaser release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
